import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import imageLoader from "../imageLoader";
import styles from "../styles/Home.module.css";
import { Character, GetCharacterResults } from "../types";

/**
 *
 * Characters is a type of Character, and its going to be an array of characters
 */

const Home: NextPage<{ characters: Character[] }> = ({ characters }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {JSON.stringify(characters)} */}
      {characters.map((character) => {
        return (
          <div key={character.id}>
            <Link href={`/characters/${character.id}`}>
              <h3>{character.name}</h3>
            </Link>
            <Image
              loader={imageLoader} // needed if you want to build
              unoptimized // we don't want nextJS to optimize these because they are already hosted
              src={character.image}
              alt={character.name}
              width={200}
              height={200}
            />
          </div>
        );
      })}
    </div>
  );
};

/**
 *
 * getStaticProps
 * - is going to run when you build your application
 * - use to build a static website
 *
 * getServerSideProps
 * - means you have to run your application in lambda functions
 * - use to build a dynamc server rendering webiste
 */

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://rickandmortyapi.com/api/character"); // returns an array of characters
  const { results }: GetCharacterResults = await res.json(); //deconstructure results

  return {
    props: {
      characters: results,
    },
  };
};

export default Home;
